#!/bin/bash

nov_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$nov_dir/november-init"

if ishelp $1; then
    echo "November -- a simple screenshooting utility"
    echo "Usage: $(basename $0) [option]"
    echo
    echo "Options:"
    echo "  screen"
    echo "  window"
    echo "  selection"
    echo
    echo "You need to configure November before usage, see https://github.com/nibogd/november"
    exit
fi

depend "maim"
depend "slop"

checkconf
source "$configfile"

timestamp=$screenshot_prefix`date +%Y%m%d_%H%M%S`
file="$screenshots_dir/$timestamp.png"

make_shadow() {
   convert $1 \( +clone -background black -shadow 80x20+0+15 \) +swap -background "$background" -layers merge +repage $1
}

case $1 in
    screen)
        maim $file
        code=$?
        shadow=$screen_shadow
        ;;
    window)
        maim -i $(xdotool getactivewindow) $file
        code=$?
        shadow=$window_shadow
        ;;
    selection)
        maim -i $(xdotool getactivewindow) -s $file
        code=$?
        shadow=$selection_shadow
        ;;
    *)
        echo 'Unknown option. Run -h to see help.'
        exit 1
        ;;
esac

if [ "$code" = '0' ]; then
    $shadow && do_shadow $file
    clip -t image/png < $file
    notify  "Screenshot" "Saved to $file!"

    echo "$file" > $last_shot_path
fi
exit $code

