#!/bin/bash

nov_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$nov_dir/november-init"

if ishelp $1; then
    echo "November-helper"
    echo "Usage: $(basename $0) [option]"
    echo
    echo "Options:"
    echo "  cast - open last screencast (player specified in ~/.november.confi)"
    echo "  shot - open last screenshot"
    echo "  imgur - upload last screenshot to imgur and copy link"
    echo "  telegram [chat] - send last screenshot to [chat] in Telegram"
    echo
    echo "All imgur image links and deletion links are stored in $imgur_delete_url"
    echo
    echo "You need to configure November before usage, see https://github.com/nibogd/november"
    exit
fi

depend "curl"

checkconf
source "$configfile"


imgur() {
    resp=`curl -H "Authorization: Client-ID $imgur_api_key" -F "image=@$1" https://api.imgur.com/3/image.xml 2>/dev/null`
    if [ $? -ne 0 ] || [ `echo $resp | grep -c "success=\"0\""` -gt 0 ]; then
        echo "Upload failed" >&2
        errors=true
        url="Upload to imgur failed"
    else
        url=`echo $resp | sed -rne 's/.*<link>([A-Za-z0-9:\/.]*).*/\1 /p'`
        deleteurl="http://imgur.com/delete/`echo $resp | sed -rne 's/.*<deletehash>([A-Za-z0-9:\/.]*).*/\1 /p'`"
        echo "$1 -- $url -- $deleteurl" >> $imgur_delete_url
    fi

    
    echo $url | clip 

    notify "Imgur" "Upload finished!"
}

telegram() {
    # $1 -- chat name (as in $telegram_chats)
    # $2 -- Photo or Document or Video
    # $3 -- file name 
    if [ -f $telegram_chats ]; then
        declare -A chats
        source "$telegram_chats"
        if [ "${chats["$1"]}" != "" ]; then
            result=$(curl "https://api.telegram.org/bot$telegram_token/send$2?chat_id=${chats["$1"]}" -F "${2,,}=@$3" 2> /dev/null)
            if [ "`echo $result | grep -c '"ok":false'`" -gt 0 ]; then
                notify "Telegram" "Upload failed"
            else
                notify "Telegram" "$2 sent!"
            fi
        else
            echo "No such chat $1. Please edit the $telegram_chats file."
            exit 1
        fi
    else
        cp $nov_dir/november-telegram.sample.conf $telegram_chats
        echo "I've created a configuration file for Telegram chats at $telegram_chats. Please edit it and come back!"
        exit 1
    fi
}

case $1 in
    shot)
        file="`cat $last_shot_path`"
        $image_viewer "$file" &
        clip -t image/png < $file &
        ;;
    cast)
        $video_player "`cat $last_cast_path`" &
        ;;
    imgur)
        imgur `cat $last_shot_path`
        ;;
    telegram)
        case $3 in
	    cast)
		send_what=Video
		filename="`cat $last_cast_path`"
		;;
	    shot|'')
	    	send_what=Photo
		filename="`cat $last_shot_path`"
		;;
	    *)
	        echo "Unknown attachment type. Can be cast or shot|*empty*, not $3"
		exit 1
		;;
        esac

        if [ "$4" = "as_doc" ]; then
            send_what=Document
	fi

        telegram $2 $send_what $filename
        ;;
    *)
        echo 'Unknown option. Run -h to see help.'
        exit 1
        ;;
esac

